DefaultContentLanguage = "en"
baseURL = "https://levites-voice-development.netlify.com/"
[languages.en]
languageName = "English"
title = "Levite's Voice"
weight = 1
[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = 0
[[languages.en.menu.main]]
name = "About"
url = "/about"
weight = 1
[languages.en.params]
linkedin = "https://linkedin.com/whoever"
[languages.ru]
languageName = "Russian"
title = "Mon blogue"
weight = 2
[[languages.ru.menu.main]]
name = "Home"
url = "/"
weight = 0
[languages.ru.params]
linkedin = "https://linkedin.com/fr/whoever"
