baseURL = "http://example.org/"
DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "Levite's Voice"
    languageName = "English"
    weight = 1
    [languages.en.params]
      linkedin = "https://linkedin.com/whoever"
  [languages.ru]
    title = "Mon blogue"
    languageName = "Russian"
    weight = 2
    [languages.ru.params]
      linkedin = "https://linkedin.com/fr/whoever"
      [languages.fr.params.navigation]
        help = "Aide"