baseURL = "http://example.org/"
DefaultContentLanguage = "en"

[languages.en]
title = "Levite's Voice"
languageName = "English"
weight = 1

[[languages.en.menu.main]]
url    = "/"
name   = "Home"
weight = 0

[[languages.en.menu.main]]
url    = "/about"
name   = "About"
weight = 1

[languages.en.params]
linkedin = "https://linkedin.com/whoever"

[languages.ru]
title = "Mon blogue"
languageName = "Russian"
weight = 2

[[languages.ru.menu.main]]
url    = "/"
name   = "Home"
weight = 0

[languages.ru.params]
linkedin = "https://linkedin.com/fr/whoever"